const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
const USER_FETCH_FAILURE = "USER_FETCH_FAILURE";

export {USER_FETCH_REQUEST, USER_FETCH_SUCCESS, USER_FETCH_FAILURE};